# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested


title:		           "Portfly"
description:	       "As nossas experiencias como devs"
author:              "Korzre & Caio Mitsuo"
